version: '2'
services:
  cabin_db:
    image: mysql:latest
    volumes:
      - "./dbtier/sql-scripts:/docker-entrypoint-initdb.d/"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: company
      MYSQL_USER: dbtier
      MYSQL_PASSWORD: supersecret